name = "surreal"
version = "0.1.3"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
json_value = ">= 1.0.0 and < 2.0.0"
birl = ">= 2.0.0 and < 3.0.0"
collie = ">= 2.0.0 and < 3.0.0"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
gjwt = ">= 2.0.1 and < 3.0.0"
sceall = ">= 1.1.0 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
str = ">= 2.1.1 and < 3.0.0"
module = { git = "https://github.com/Remy2701/module.git", ref = "main" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 2.0.2 and < 3.0.0"
